### ISSUE TITLE
Error in code examples

### ISSUE THREAD

**Issue by agneta-rung** [OpenTNF/OpenTNF-library#1]
There are code examples on the page https://github.com/OpenTNF/OpenTNF-library saying that you should call method OpenConnection() on a GeoPackageDatabase. There is no such (public) method though, in the latest version.

**Comment by adellestrand** [comment]
Hi,

I can see the examples are not accurate to the current version. Will update. 

You should use OpenGeoPackageDatabase() method to connect to an exisitng databse.
